### ISSUE TITLE
aliexpress.com: "Add to Cart" or "Add to Wish List" broken for some items

### ISSUE THREAD

**Issue by davidhedlund** [davidhedlund/LBWT#5]
- Can not Add to Cart example: ​https://www.aliexpress.com/item/Hilda-HLD-400W-0-6-6-5mm-Electric-Die-Grinder-220V-400W-Variable-Speed-Multifunctional-Electric/32640458587.html. Message: Failed to add, please refresh the page and re-click the "Add to Cart". 
- Can not add to wish list example: ​https://www.aliexpress.com/item/10-Pcs-Lot-Waterproof-Aluminum-Pill-Medicine-Box-Case-Bottle-Drug-Container-Holder-with-Keychain-Health/32581171076.html

**Comment by TA2WK** [comment]
Solution is simple here http://www.cazda.com/en_US/aliexpress-sepete-ekleme-basarisiz-hatasi/
